language: cpp
compiler: gcc
os:
  - linux
  - osx
osx_image: xcode7.3
cache:
  directories:
    - "$HOME/dependencies"
    - "$HOME/projects"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - linux-libc-dev:i386
      - gcc-4.9
      - gcc-4.9-multilib
      - g++-4.9
      - g++-4.9-multilib
install:
  - export MODULE_NAME="serversecure"
  - export DEPENDENCIES="$HOME/dependencies"
  - export GARRYSMOD_COMMON="$DEPENDENCIES/garrysmod_common"
  - export SOURCE_SDK="$DEPENDENCIES/sourcesdk-minimal"
  - export TARGET_OS=$TRAVIS_OS_NAME
  - if [ $TRAVIS_OS_NAME = "osx" ]; then
      export PREMAKE5="$DEPENDENCIES/macosx/premake-core/premake5 --cc=clang";
      export PROJECT_OS=macosx;
    elif [ $TRAVIS_OS_NAME = "linux" ]; then
      export PREMAKE5="$DEPENDENCIES/linux/premake-core/premake5";
      export PROJECT_OS=linux;
      export CXX=g++-4.9;
      export CC=gcc-4.9;
    fi
script: "$CI_PROJECT_DIR/ci.sh"
deploy:
  provider: releases
  skip_cleanup: true
  file: "gmsv_${MODULE_NAME}_$TARGET_OS.dll"
  on:
    tags: true
  api_key:
    secure: DMW0byGslhkzT3m4xgGHPIg8IsbmgfdDvwhyiDOyssftqcZnddl7Yit1IS/4q/StMeagWrCF+cbYee0n1v5QtOUu3Cr5EXBFgzwHmvYdTGHuEbMwcR/uM5R6UzgXpNn363mWiyYP5txuA2dX8DPULMZU/BCCxH9/Uuk6nNC8KfoSTAjYQTRt+VToNVEBKcZJ/VWlP2LWketQyY83r0OFnwbXihpw+Z/WAmt3FUfvtrAdBnOi3vxHCoib6RvHcUp4FLIrLEkmAjrFwrhKn/miPWWpCmh+Ou4YXSVuE5Wzj+zNY/6XpS4l4VDVu5zgu4T0RsYxS/9f9QoYPTo19By9NcWgXY9kdUcxAoRSv9JIPE4779a7THrXvnlrRu1B+wo9NAnxjK2rTmdFlLQrqR8uaSXKgTOyRlFHao5/AX82vss44XcWqM8dNQk8tjc4uwb9n1WAnDIKJ9KBKCD5EmfeVMTPEuGfIQJmHcNc/VLzBiD8rrLDP+w4zcK5QqLNr3jqes0u/OJz+XFAehkmIs6rt9Lt8D66h2hgu/OYwsdIc/1ZvyySZrVzcSzmGlgQbwQheXPlFcdQncvQH87LQmj48Vj49tPbwWcmiAd/3tHNSS1ZcNc2VrMSNEJZ0lS2zgg+0i7FBYYAC9vbQAtxN7MI+6SwL4en5DjVHW3AKRlTTIw=
