language: cpp
compiler: gcc
os:
  - linux
  - osx
cache:
  directories:
    - $HOME/dependencies
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - linux-libc-dev:i386
      - gcc-4.9
      - gcc-4.9-multilib
      - g++-4.9
      - g++-4.9-multilib
branches:
  only:
    - master
install:
  - export GARRYSMOD_COMMON=$HOME/dependencies/garrysmod_common
  - export SOURCE_SDK=$HOME/dependencies/sourcesdk-minimal
  - if [[ ${TRAVIS_OS_NAME} = osx ]]; then
      export BINARY_PATH=gmsv_serversecure_mac.dll;
      export PREMAKE5="$HOME/dependencies/premake-core/premake5 --cc=clang";
      export PROJECT_OS=macosx;
    elif [[ ${TRAVIS_OS_NAME} = linux ]]; then
      export BINARY_PATH=gmsv_serversecure_linux.dll;
      export PREMAKE5=$HOME/dependencies/premake-core/premake5;
      export PROJECT_OS=linux;
      export CXX=g++-4.9;
      export CC=gcc-4.9;
    fi
  - export REPO=`pwd`
  - cd $HOME/dependencies
  - if [ ! -f "garrysmod_common/premake5.lua" ]; then
      echo "garrysmod_common directory is empty, doing git clone of the remote repo";
      git clone --recursive https://github.com/danielga/garrysmod_common.git;
    else
      echo "garrysmod_common directory is good, pulling any latest changes";
      cd garrysmod_common;
      git pull;
      git submodule update --init --recursive;
      cd ..;
    fi
  - if [ ! -f "sourcesdk-minimal/LICENSE" ]; then
      echo "sourcesdk-minimal directory is empty, doing git clone of the remote repo";
      git clone https://github.com/danielga/sourcesdk-minimal.git;
    else
      echo "sourcesdk-minimal directory is good, pulling any latest changes";
      cd sourcesdk-minimal;
      git pull;
      cd ..;
    fi
  - if [ ! -f "premake-core/premake5" ]; then
      echo "premake-core directory is empty, doing git clone of the remote repo and bootstrap";
      git clone --recursive https://github.com/premake/premake-core.git;
      mv premake-core premake-core-build;
      cd premake-core-build;
      make -f Bootstrap.mak $TRAVIS_OS_NAME;
      cd ..;
      mkdir premake-core;
      cp premake-core-build/bin/release/premake5 premake-core;
    fi
before_script: cd $REPO/projects && $PREMAKE5 gmake
script:
  - cd $PROJECT_OS/gmake
  - make
before_deploy: cd release
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: ImPHIUbFzQqYf4MPKwuILsX3ptMacIB8vTwE5fsOY2RjewQqy4f9fbFa7iSvPOOKPEp56DFGzwnNHntH5JPTfEZEFLl5fbRZaf3bdMUwZNJGVqEpbKo9/lN4xMDLiUfuLZAQ4Vgt9qUG+L0pi4YEdPq/vATHNWbdUQLMT5lolRUSq/qopBouXwuZkT3GMchEZpj/Chors+N5+VuSxGwfi7Ih0U5pLpJZQCKTaV0WbwSuKhGSV2QCKlyFrTuFNFgbOu0M54MFpIYYeb1dmHSYIkjG31YWBKsQSx+ME+J7avaLRHMQFZN/suOmkJ/AIBQ7JD1NFpC2Pp8AIpP0j9f0S+L+YYv7yjjrv0Uu0aELY2AwEdhpVmY9qqmuZkQ5Zh7qUNIGbOJksHoCQ4NvBK/eOeUovyVEwIQ8Pwbbkj9tJ57U8gKRq8hwejMt04AxccuOdlHjYH4jioDOzEiV9R2NjlBzcru15I1VX+oqNWabIMRYmI9e1Paf9vrug2zX6zH7tbn3EEjZ9hgEHmGC3OZ8hBw2pVNEQxOZg5wc/piGmuzn0U5gOkSpNyMPvzNNL8Hq3w8hgQhNQZ5BKFR9I4kGwBwW+rirW2JxJAf6gvh8+nCkIDfJemCcnLlSzYQ0yquT3pddj8kZY1Z2t9IZBN8ElaiGaof+ZTv/2xeR7o+L0LU=
  file: $BINARY_PATH
