language: cpp
if: tag IS present
git:
  depth: 1
env:
  global:
    - MODULE_NAME=serversecure.core
      REPOSITORY_DIR="$TRAVIS_BUILD_DIR"
      DEPENDENCIES="$TRAVIS_BUILD_DIR/dependencies"
      GARRYSMOD_COMMON="$TRAVIS_BUILD_DIR/dependencies/garrysmod_common"
      GARRYSMOD_COMMON_REPOSITORY="https://github.com/danielga/garrysmod_common.git"
      GARRYSMOD_COMMON_BRANCH=master
      SOURCE_SDK="$TRAVIS_BUILD_DIR/dependencies/sourcesdk-minimal"
      SOURCE_SDK_REPOSITORY="https://github.com/danielga/sourcesdk-minimal.git"
      SOURCE_SDK_BRANCH=master
      BUILD_SCRIPT="$TRAVIS_BUILD_DIR/dependencies/garrysmod_common/build/build.sh"
      BOOTSTRAP_URL="https://raw.githubusercontent.com/danielga/garrysmod_common/master/build/bootstrap.sh"
      TARGET_OS="$TRAVIS_OS_NAME"
      TARGET_OS_64="${TRAVIS_OS_NAME}64"
      TARGET_ARCHITECTURE=x86
      TARGET_ARCHITECTURE_64=x86_64
      PROJECT_GENERATOR_VERSION=2
      COMPILER_PLATFORM=gmake
      DISABLE_X86_64_BUILD=true
matrix:
  include:
    - os: linux
      dist: bionic
      compiler: gcc
      addons:
        apt:
          packages:
            - linux-libc-dev:i386
            - g++-8-multilib
      env:
        - PREMAKE5="$TRAVIS_BUILD_DIR/dependencies/linux/premake-core/premake5"
          PROJECT_OS=linux
          PREMAKE5_URL="https://github.com/premake/premake-core/releases/download/v5.0.0-alpha14/premake-5.0.0-alpha14-linux.tar.gz"
      before_install:
        - export CC=gcc-8
          export CXX=g++-8
    - os: osx
      osx_image: xcode9.4
      env:
        - PREMAKE5="$TRAVIS_BUILD_DIR/dependencies/macosx/premake-core/premake5"
          PROJECT_OS=macosx
          PREMAKE5_URL="https://github.com/premake/premake-core/releases/download/v5.0.0-alpha14/premake-5.0.0-alpha14-macosx.tar.gz"
install: "curl -s -L \"$BOOTSTRAP_URL\" | bash"
script: "$BUILD_SCRIPT"
deploy:
  provider: releases
  skip_cleanup: true
  file:
    - "${TRAVIS_BUILD_DIR}/projects/${PROJECT_OS}/${COMPILER_PLATFORM}/${TARGET_ARCHITECTURE}/Release/gmsv_${MODULE_NAME}_${TARGET_OS}.dll"
    - "${TRAVIS_BUILD_DIR}/projects/${PROJECT_OS}/${COMPILER_PLATFORM}/${TARGET_ARCHITECTURE_64}/Release/gmsv_${MODULE_NAME}_${TARGET_OS_64}.dll"
  on:
    tags: true
  api_key:
    secure: DMW0byGslhkzT3m4xgGHPIg8IsbmgfdDvwhyiDOyssftqcZnddl7Yit1IS/4q/StMeagWrCF+cbYee0n1v5QtOUu3Cr5EXBFgzwHmvYdTGHuEbMwcR/uM5R6UzgXpNn363mWiyYP5txuA2dX8DPULMZU/BCCxH9/Uuk6nNC8KfoSTAjYQTRt+VToNVEBKcZJ/VWlP2LWketQyY83r0OFnwbXihpw+Z/WAmt3FUfvtrAdBnOi3vxHCoib6RvHcUp4FLIrLEkmAjrFwrhKn/miPWWpCmh+Ou4YXSVuE5Wzj+zNY/6XpS4l4VDVu5zgu4T0RsYxS/9f9QoYPTo19By9NcWgXY9kdUcxAoRSv9JIPE4779a7THrXvnlrRu1B+wo9NAnxjK2rTmdFlLQrqR8uaSXKgTOyRlFHao5/AX82vss44XcWqM8dNQk8tjc4uwb9n1WAnDIKJ9KBKCD5EmfeVMTPEuGfIQJmHcNc/VLzBiD8rrLDP+w4zcK5QqLNr3jqes0u/OJz+XFAehkmIs6rt9Lt8D66h2hgu/OYwsdIc/1ZvyySZrVzcSzmGlgQbwQheXPlFcdQncvQH87LQmj48Vj49tPbwWcmiAd/3tHNSS1ZcNc2VrMSNEJZ0lS2zgg+0i7FBYYAC9vbQAtxN7MI+6SwL4en5DjVHW3AKRlTTIw=
